# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis\Tabulation.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LeftBorder = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LeftBorder.setGeometry(QtCore.QRect(280, 270, 120, 30))
        self.LeftBorder.setObjectName("LeftBorder")
        self.RightBorder = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.RightBorder.setGeometry(QtCore.QRect(280, 330, 120, 30))
        self.RightBorder.setObjectName("RightBorder")
        self.Step = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Step.setGeometry(QtCore.QRect(280, 390, 120, 30))
        self.Step.setObjectName("Step")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 240, 120, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 300, 120, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 360, 120, 30))
        self.label_3.setObjectName("label_3")
        self.FunctionLabel = QtWidgets.QLabel(self.centralwidget)
        self.FunctionLabel.setGeometry(QtCore.QRect(20, 20, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.FunctionLabel.setFont(font)
        self.FunctionLabel.setObjectName("FunctionLabel")
        self.Output = QtWidgets.QTextEdit(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(20, 70, 241, 351))
        self.Output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Output.setObjectName("Output")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 130, 120, 81))
        self.groupBox.setObjectName("groupBox")
        self.PrintOnScreen = QtWidgets.QCheckBox(self.groupBox)
        self.PrintOnScreen.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.PrintOnScreen.setObjectName("PrintOnScreen")
        self.PrintInFile = QtWidgets.QCheckBox(self.groupBox)
        self.PrintInFile.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.PrintInFile.setObjectName("PrintInFile")
        self.PrintInArray = QtWidgets.QCheckBox(self.groupBox)
        self.PrintInArray.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.PrintInArray.setObjectName("PrintInArray")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Tabulate = QtWidgets.QAction(MainWindow)
        self.Tabulate.setObjectName("Tabulate")
        self.Clear = QtWidgets.QAction(MainWindow)
        self.Clear.setObjectName("Clear")
        self.About = QtWidgets.QAction(MainWindow)
        self.About.setObjectName("About")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.menu.addAction(self.Tabulate)
        self.menu.addAction(self.Clear)
        self.menu_2.addAction(self.About)
        self.menu_2.addAction(self.Exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ліва межа"))
        self.label_2.setText(_translate("MainWindow", "Права межа"))
        self.label_3.setText(_translate("MainWindow", "Крок"))
        self.FunctionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">y = sin(x) + 1</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Виведення"))
        self.PrintOnScreen.setText(_translate("MainWindow", "На екран"))
        self.PrintInFile.setText(_translate("MainWindow", "У файл"))
        self.PrintInArray.setText(_translate("MainWindow", "У масив"))
        self.menu.setTitle(_translate("MainWindow", "Обчислення"))
        self.menu_2.setTitle(_translate("MainWindow", "Кінець"))
        self.Tabulate.setText(_translate("MainWindow", "Протабулювати"))
        self.Clear.setText(_translate("MainWindow", "Отчистити поля"))
        self.About.setText(_translate("MainWindow", "Про програму"))
        self.Exit.setText(_translate("MainWindow", "Кінець"))
